@echo off
REM Machine Summary Block
REM {"file":"setup_glint_env.bat","purpose":"Sets up glint command in Windows PATH for global access.","exports":[],"depends_on":["builds/desktop/cmake"],"notes":["windows_path_setup","wrapper_creation","environment_configuration"]}
REM Human Summary
REM Windows setup script that creates a glint wrapper and adds it to PATH for convenient command-line access.

echo ========================================
echo Glint CLI Environment Setup (Windows)
echo ========================================
echo.

REM Get the repository root directory (where this script is located)
set REPO_ROOT=%~dp0
set REPO_ROOT=%REPO_ROOT:~0,-1%

echo Repository root: %REPO_ROOT%
echo.

REM Create bin directory if it doesn't exist
set BIN_DIR=%REPO_ROOT%\bin
if not exist "%BIN_DIR%" (
    echo Creating bin directory: %BIN_DIR%
    mkdir "%BIN_DIR%"
)

REM Create wrapper script
set WRAPPER=%BIN_DIR%\glint.bat
echo Creating wrapper script: %WRAPPER%

(
echo @echo off
echo REM Glint CLI Wrapper - Auto-generated by setup_glint_env.bat
echo REM This script finds and executes the glint executable
echo.
echo setlocal
echo.
echo REM Find the glint executable (prefer Release, fallback to Debug^)
echo set GLINT_EXE=
echo if exist "%%~dp0..\builds\desktop\cmake\Release\glint.exe" (
echo     set GLINT_EXE=%%~dp0..\builds\desktop\cmake\Release\glint.exe
echo ^) else if exist "%%~dp0..\builds\desktop\cmake\Debug\glint.exe" (
echo     set GLINT_EXE=%%~dp0..\builds\desktop\cmake\Debug\glint.exe
echo ^) else (
echo     echo ERROR: glint.exe not found. Please build the project first.
echo     echo Run: cmake --build builds/desktop/cmake --config Release
echo     exit /b 1
echo ^)
echo.
echo REM Change to repository root for correct asset paths
echo cd /d "%%~dp0.."
echo.
echo REM Execute glint with all arguments
echo "%%GLINT_EXE%%" %%*
echo.
echo REM Preserve exit code
echo exit /b %%ERRORLEVEL%%
) > "%WRAPPER%"

echo Wrapper created successfully!
echo.

REM Check if bin directory is already in PATH
echo %PATH% | findstr /I /C:"%BIN_DIR%" >nul
if %ERRORLEVEL% equ 0 (
    echo [OK] %BIN_DIR% is already in your PATH
) else (
    echo [ACTION REQUIRED] Adding %BIN_DIR% to your PATH
    echo.
    echo Please run ONE of the following commands:
    echo.
    echo Option 1 - Current session only (temporary^):
    echo     set PATH=%%PATH%%;%BIN_DIR%
    echo.
    echo Option 2 - Current user permanently (recommended^):
    echo     setx PATH "%%PATH%%;%BIN_DIR%"
    echo.
    echo Option 3 - All users permanently (requires admin^):
    echo     Open PowerShell as Administrator and run:
    echo     [Environment]::SetEnvironmentVariable("Path", $env:Path + ";%BIN_DIR%", "Machine"^)
    echo.
    echo After running one of these commands, restart your terminal.
)

echo.
echo ========================================
echo Setup Complete!
echo ========================================
echo.
echo You can now use 'glint' from anywhere!
echo.
echo Examples:
echo     glint doctor
echo     glint clean --dry-run
echo     glint render --input scene.obj --output out.png
echo.
echo Note: Make sure to build the project first if you haven't already:
echo     cmake --build builds/desktop/cmake --config Release
echo.

pause
